"""Content library for the space-shorts agent.

TOPICS is the pool the agent samples from. Keeping it in its own module keeps
agent.py focused on the pipeline and makes the list easy to grow.
"""

TOPICS = [
    "Black holes and what happens if you fall in",
    "Neutron stars spinning 700 times per second",
    "White dwarfs slowly cooling for trillions of years",
    "Magnetars with the strongest magnetic fields in the universe",
    "Red giants swallowing their planets",
    "Supernovas brighter than entire galaxies",
    "Gamma ray bursts the most powerful explosions ever",
    "Binary star systems orbiting each other",
    "Rogue stars ejected from galaxies at millions of mph",
    "Venus hotter than Mercury despite being farther from the Sun",
    "Jupiters Great Red Spot storm bigger than Earth",
    "Saturns rings made of billions of ice chunks",
    "Titan Saturns moon with lakes of liquid methane",
    "Europas ocean hidden under miles of ice",
    "Uranus rotates on its side",
    "Neptunes wind speeds of 1500 mph",
    "Plutos heart-shaped nitrogen glacier",
    "The Milky Way is on a collision course with Andromeda",
    "Supermassive black holes at the center of every galaxy",
    "The Great Attractor pulling everything including us",
    "Quasars brighter than a trillion suns",
    "Dark matter making up 27 percent of the universe",
    "Dark energy causing the universe to expand faster",
    "Time slows down near massive objects time dilation",
    "Wormholes shortcuts through space-time",
    "The universe might be inside a black hole",
    "Parallel universes in the multiverse theory",
    "Hawking radiation black holes slowly evaporate",
    "Spaghettification what happens near a black hole",
    "The Big Bang came from a single point smaller than an atom",
    "Quantum entanglement connecting particles across the universe",
    "The Voyager probe leaving our solar system after 46 years",
    "The James Webb telescope seeing the first galaxies ever formed",
    "Apollo 11 moon landing and what they left behind",
    "The ISS traveling at 17500 mph orbiting Earth 16 times daily",
    "SpaceX Starship the biggest rocket ever built",
    "The Mars rovers discovering ancient riverbeds",
    "Hubbles Deep Field photo 10000 galaxies in one image",
    "Plans to build a base on the Moon by 2030",
    "The Drake equation estimating alien civilizations",
    "The Fermi paradox where is everyone",
    "The Wow signal unexplained radio burst from space",
    "TRAPPIST-1 system with 7 Earth-sized planets",
    "Panspermia life spreading through asteroids",
    "A day on Venus is longer than a year on Venus",
    "The footprints on the Moon will last millions of years",
    "The Sun loses 4 million tons of mass every second",
    "There are more stars than grains of sand on Earth",
    "A teaspoon of neutron star weighs a billion tons",
    "Space smells like seared steak and hot metal",
    "What existed before the Big Bang",
    "Every atom in your body was made inside a star",
    "The largest black hole is 40 billion times the mass of our Sun",
    "Pulsars are the most accurate clocks in the universe",
    "The Pillars of Creation where new stars are born right now",
    "Sagittarius A the supermassive black hole in our galaxy",
    "In space your body grows 2 inches taller",
    "The Moon is moving away from Earth 1.5 inches per year",
    "One day on Jupiter is only 10 hours long",
    "Olympus Mons on Mars is 3 times taller than Mount Everest",
    "Venus spins backwards compared to most planets",
    "The rings of Saturn will disappear in 100 million years",
    "Solar flares that could knock out all electricity on Earth",
    "Space debris 27000 pieces of junk orbiting Earth right now",
    "The asteroid that killed the dinosaurs and what it left behind",
    "Yuri Gagarin the first human in space in 1961",
    "How astronauts sleep eat and go to the bathroom in space",
    "Terraforming Mars to make it habitable for humans",
    "Mining asteroids for gold platinum and rare minerals",
    "Dyson spheres built around stars to harvest all their energy",
    "Fast Radio Bursts mysterious signals from across the universe",
    "Oumuamua the mysterious interstellar object that visited our solar system",
    "Enceladus shooting water geysers into space from its ocean",
    "If the Sun were a door the Earth would be a coin",
    "The nearest star is so far light takes 4 years to reach us",
    "Saturn would float on water because it is less dense",
    "A year on Mercury is shorter than its day",
    "Stars older than the universe itself",
    "Io the most volcanically active world in the solar system",
    "Mercury shrinks a little more every year",
    "There are zombie stars that refuse to die",
    "Titan could support life unlike anything we know",
    "The search for biosignatures on exoplanet atmospheres",
]
